--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GabBiswajit/Profile-ui
build-by-default: true
branches:
- main
projects:
  Profile-ui:
    path: ""
    lint: false
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^3.0.0
        branch: stable
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
