name: ProfileUI
main: Biswajit\ProfileUI\Profile
api: 5.0.0
author: Biswajit
version: 1.1.0
softdepend: ["BedrockEconomy", "EconomyAPI", "PurePerms"]

commands:
  profile:
    description: Use Command To Check Your Profile Stats
    permission: Profile-ui.cmd.use

permissions:
  Profile-ui.cmd.use:
    description: ProfileUI Permission
    default: true
