name: ProfileUI
main: Biswajit\Profile
api: 5.0.0
author: Biswajit
version: 1.0.0

commands:
  profile:
    description: Use Command To Check Your Profile Stats
    permission: profileui.cmd.use

permissions:
  profileui.cmd.use:
    description: ProfileUI Permission
    default: true
